### ISSUE TITLE
Error "'int' object has no attribute '__getitem__'" in img_to_text.py 

### ISSUE THREAD

**Issue by imrankhurram** [computationalmedia/semstyle#4]
I am getting this error while running `img_to_text.py` on my folder of 2 images.

```
Traceback (most recent call last):
  File "img_to_text.py", line 475, in <module>
    main()
  File "img_to_text.py", line 471, in main
    test(r, args.test_folder)
  File "img_to_text.py", line 331, in test
    text = s2s.test(s2s_data, untok)
  File "/home/ikhurram/stylizedcaption/semstyle/code/seq2seq_pytorch.py", line 253, in test
    dec_tensor = generate(setup_data['enc'], setup_data['dec'], enc_padded_text[i*BATCH_SIZE:(i+1)*BATCH_SIZE])
  File "/home/ikhurram/stylizedcaption/semstyle/code/seq2seq_pytorch.py", line 161, in generate
    order, enc_pp, enc_lengths = make_packpadded(0, enc_padded_text.shape[0], enc_padded_text)
  File "/home/ikhurram/stylizedcaption/semstyle/code/seq2seq_pytorch.py", line 200, in make_packpadded
    leng = torch.tensor(lengths[order])
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by imrankhurram** [comment]
ok solved it. Changed the path of model so that I contains absolute path.
